In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix 
from sklearn import metrics 
from sklearn.metrics import roc_auc_score 
from sklearn.metrics import roc_curve 
from sklearn.metrics import classification_report 
from sklearn.metrics import f1_score 
from sklearn.ensemble import RandomForestClassifier
from sklearn. tree import DecisionTreeClassifier, plot_tree 
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv('career_pred.csv')

In [3]:
df.head()

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,...,Interested Type of Books,Salary Range Expected,In a Realtionship?,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,69,63,78,87,94,94,87,84,61,9,...,Prayer books,salary,no,stubborn,Management,salary,hard worker,yes,no,Database Developer
1,78,62,73,60,71,70,73,84,91,12,...,Childrens,salary,yes,gentle,Technical,salary,hard worker,no,yes,Portal Administrator
2,71,86,91,87,61,81,72,72,94,11,...,Travel,Work,no,stubborn,Management,work,hard worker,no,yes,Portal Administrator
3,76,87,60,84,89,73,62,88,69,7,...,Romance,Work,yes,gentle,Management,work,smart worker,yes,yes,Systems Security Administrator
4,92,62,90,67,71,89,73,71,73,4,...,Cookbooks,salary,no,stubborn,Management,work,hard worker,yes,yes,Business Systems Analyst

In [4]:
df.isna()

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,...,Interested Type of Books,Salary Range Expected,In a Realtionship?,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
df=df.dropna()
df.isna().sum().sum()

0

In [6]:
df.duplicated()
df.drop_duplicates()

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,...,Interested Type of Books,Salary Range Expected,In a Realtionship?,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,69,63,78,87,94,94,87,84,61,9,...,Prayer books,salary,no,stubborn,Management,salary,hard worker,yes,no,Database Developer
1,78,62,73,60,71,70,73,84,91,12,...,Childrens,salary,yes,gentle,Technical,salary,hard worker,no,yes,Portal Administrator
2,71,86,91,87,61,81,72,72,94,11,...,Travel,Work,no,stubborn,Management,work,hard worker,no,yes,Portal Administrator
3,76,87,60,84,89,73,62,88,69,7,...,Romance,Work,yes,gentle,Management,work,smart worker,yes,yes,Systems Security Administrator
4,92,62,90,67,71,89,73,71,73,4,...,Cookbooks,salary,no,stubborn,Management,work,hard worker,yes,yes,Business Systems Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,83,67,62,63,81,74,90,84,69,4,...,Journals,Work,yes,stubborn,Management,salary,smart worker,yes,no,Technical Engineer
19996,80,69,83,87,82,66,66,92,67,7,...,Cookbooks,salary,no,stubborn,Management,salary,hard worker,no,yes,E-Commerce Analyst
19997,83,70,80,87,64,85,69,94,88,7,...,Drama,Work,yes,gentle,Technical,work,hard worker,no,yes,Business Intelligence Analyst
19998,68,87,91,88,66,74,61,87,61,5,...,Travel,Work,no,gentle,Management,work,smart worker,yes,no,Software Quality Assurance (QA) / Testing
19999,73,77,74,84,70,65,92,73,90,7,...,Comics,Work,no,gentle,Management,work,hard worker,yes,no,Applications Developer

In [7]:
df.dtypes

Acedamic percentage in Operating Systems     int64
percentage in Algorithms                     int64
Percentage in Programming Concepts           int64
Percentage in Software Engineering           int64
Percentage in Computer Networks              int64
Percentage in Electronics Subjects           int64
Percentage in Computer Architecture          int64
Percentage in Mathematics                    int64
Percentage in Communication skills           int64
Hours working per day                        int64
Logical quotient rating                      int64
hackathons                                   int64
coding skills rating                         int64
public speaking points                       int64
can work long time before system?           object
self-learning capability?                   object
Extra-courses did                           object
certifications                              object
workshops                                   object
talenttests taken?                          object
olympiads                                   object
reading and writing skills                  object
memory capability score                     object
Interested subjects                         object
interested career area                      object
Job/Higher Studies?                         object
Type of company want to settle in?          object
Taken inputs from seniors or elders         object
interested in games                         object
Interested Type of Books                    object
Salary Range Expected                       object
In a Realtionship?                          object
Gentle or Tuff behaviour?                   object
Management or Technical                     object
Salary/work                                 object
hard/smart worker                           object
worked in teams ever?                       object
Introvert                                   object
Suggested Job Role                          object
dtype: object

In [8]:
df = df.drop('Acedamic percentage in Operating Systems', axis=1)

In [9]:
df = df.drop('percentage in Algorithms', axis=1)

In [10]:
df = df.drop('Percentage in Programming Concepts', axis=1)

In [11]:
df = df.drop('Percentage in Software Engineering', axis=1)

In [12]:
df = df.drop('Percentage in Computer Networks', axis=1)

In [13]:
df = df.drop('Percentage in Electronics Subjects', axis=1)

In [14]:
df = df.drop('Percentage in Computer Architecture', axis=1)

In [15]:
df = df.drop('Percentage in Mathematics', axis=1)

In [16]:
df = df.drop('Percentage in Communication skills', axis=1)

In [17]:
df = df.drop('Logical quotient rating', axis=1)

In [18]:
df = df.drop('hackathons', axis=1)

In [19]:
df = df.drop('coding skills rating', axis=1)

In [20]:
df = df.drop('can work long time before system?', axis=1)

In [21]:
df = df.drop('certifications', axis=1)

In [22]:
df = df.drop('workshops', axis=1)

In [23]:
df = df.drop('talenttests taken?', axis=1)

In [24]:
df = df.drop('olympiads', axis=1)

In [25]:
df = df.drop('interested career area ', axis=1)

In [26]:
df = df.drop('Job/Higher Studies?', axis=1)

In [27]:
df = df.drop('Type of company want to settle in?', axis=1)

In [28]:
df = df.drop('Taken inputs from seniors or elders', axis=1)

In [29]:
df = df.drop('Salary Range Expected', axis=1)

In [30]:
df = df.drop('In a Realtionship?', axis=1)

In [31]:
df.dtypes

Hours working per day          int64
public speaking points         int64
self-learning capability?     object
Extra-courses did             object
reading and writing skills    object
memory capability score       object
Interested subjects           object
interested in games           object
Interested Type of Books      object
Gentle or Tuff behaviour?     object
Management or Technical       object
Salary/work                   object
hard/smart worker             object
worked in teams ever?         object
Introvert                     object
Suggested Job Role            object
dtype: object

In [32]:
df.head()

,Hours working per day,public speaking points,self-learning capability?,Extra-courses did,reading and writing skills,memory capability score,Interested subjects,interested in games,Interested Type of Books,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,9,8,yes,yes,excellent,excellent,cloud computing,no,Prayer books,stubborn,Management,salary,hard worker,yes,no,Database Developer
1,12,3,no,yes,poor,medium,networks,yes,Childrens,gentle,Technical,salary,hard worker,no,yes,Portal Administrator
2,11,3,no,yes,poor,excellent,hacking,yes,Travel,stubborn,Management,work,hard worker,no,yes,Portal Administrator
3,7,5,yes,no,medium,excellent,networks,no,Romance,gentle,Management,work,smart worker,yes,yes,Systems Security Administrator
4,4,3,no,no,poor,excellent,Computer Architecture,yes,Cookbooks,stubborn,Management,work,hard worker,yes,yes,Business Systems Analyst

In [33]:
df.shape

(20000, 16)

In [34]:
df['Suggested Job Role'].nunique()

34

In [35]:
df['Suggested Job Role'].unique()

array(['Database Developer', 'Portal Administrator',
       'Systems Security Administrator', 'Business Systems Analyst',
       'Software Systems Engineer', 'Business Intelligence Analyst',
       'CRM Technical Developer', 'Mobile Applications Developer',
       'UX Designer', 'Quality Assurance Associate', 'Web Developer',
       'Information Security Analyst', 'CRM Business Analyst',
       'Technical Support', 'Project Manager',
       'Information Technology Manager', 'Programmer Analyst',
       'Design & UX', 'Solutions Architect', 'Systems Analyst',
       'Network Security Administrator', 'Data Architect',
       'Software Developer', 'E-Commerce Analyst',
       'Technical Services/Help Desk/Tech Support',
       'Information Technology Auditor', 'Database Manager',
       'Applications Developer', 'Database Administrator',
       'Network Engineer', 'Software Engineer', 'Technical Engineer',
       'Network Security Engineer',
       'Software Quality Assurance (QA) / Testing'], dtype=object)

In [36]:
df['Suggested Job Role'].value_counts()

Suggested Job Role
Network Security Administrator               1112
Network Security Engineer                     630
Network Engineer                              621
Project Manager                               602
Database Administrator                        593
Portal Administrator                          593
Information Technology Manager                591
Software Engineer                             590
UX Designer                                   589
Design & UX                                   588
Software Developer                            587
CRM Business Analyst                          584
Business Systems Analyst                      582
Database Developer                            581
Solutions Architect                           578
Software Systems Engineer                     575
Software Quality Assurance (QA) / Testing     571
Database Manager                              570
Web Developer                                 570
CRM Technical Developer                       567
Technical Support                             565
Quality Assurance Associate                   565
Data Architect                                564
Systems Security Administrator                562
Information Technology Auditor                558
Technical Services/Help Desk/Tech Support     558
Technical Engineer                            557
Applications Developer                        551
Systems Analyst                               550
E-Commerce Analyst                            546
Information Security Analyst                  543
Business Intelligence Analyst                 540
Mobile Applications Developer                 538
Programmer Analyst                            529
Name: count, dtype: int64

In [37]:
df = df.drop_duplicates(subset=df.columns.difference(['Suggested Job Role']))

In [38]:
df.shape

(19996, 16)

In [38]:
df['Hours working per day'].unique()

array([ 9, 12, 11,  7,  4,  6, 10,  8,  5])

In [39]:
df['public speaking points'].unique()

array([8, 3, 5, 1, 6, 4, 9, 7, 2])

In [40]:
df['self-learning capability?'].unique()

array(['yes', 'no'], dtype=object)

In [41]:
df['Extra-courses did'].unique()

array(['yes', 'no'], dtype=object)

In [42]:
df['reading and writing skills'].unique()

array(['excellent', 'poor', 'medium'], dtype=object)

In [43]:
df['memory capability score'].unique()

array(['excellent', 'medium', 'poor'], dtype=object)

In [44]:
df['Interested subjects'].unique()

array(['cloud computing', 'networks', 'hacking', 'Computer Architecture',
       'programming', 'parallel computing', 'IOT', 'data engineering',
       'Software Engineering', 'Management'], dtype=object)

In [45]:
df['interested in games'].unique()

array(['no', 'yes'], dtype=object)

In [46]:
df['Interested Type of Books'].unique()

array(['Prayer books', 'Childrens', 'Travel', 'Romance', 'Cookbooks',
       'Self help', 'Drama', 'Math', 'Religion-Spirituality', 'Anthology',
       'Trilogy', 'Autobiographies', 'Mystery', 'Diaries', 'Journals',
       'History', 'Art', 'Dictionaries', 'Horror', 'Encyclopedias',
       'Action and Adventure', 'Fantasy', 'Comics', 'Science fiction',
       'Series', 'Guide', 'Biographies', 'Health', 'Satire', 'Science',
       'Poetry'], dtype=object)

In [48]:
df['Gentle or Tuff behaviour?'].unique()

array(['stubborn', 'gentle'], dtype=object)

In [49]:
df['Management or Technical'].unique()

array(['Management', 'Technical'], dtype=object)

In [50]:
df['Salary/work'].unique()

array(['salary', 'work'], dtype=object)

In [51]:
df['hard/smart worker'].unique()

array(['hard worker', 'smart worker'], dtype=object)

In [52]:
df['worked in teams ever?'].unique()

array(['yes', 'no'], dtype=object)

In [53]:
df['Introvert'].unique()

array(['no', 'yes'], dtype=object)

In [54]:
df['Interested Type of Books'].value_counts()

Interested Type of Books
Guide                    1172
Health                   1165
Self help                1151
Horror                   1133
Autobiographies           615
Fantasy                   613
Satire                    598
Biographies               589
Comics                    589
Poetry                    588
Encyclopedias             588
Prayer books              586
Anthology                 585
Science fiction           579
Art                       574
History                   572
Mystery                   569
Diaries                   566
Drama                     566
Childrens                 564
Travel                    563
Religion-Spirituality     562
Action and Adventure      557
Trilogy                   555
Dictionaries              554
Romance                   552
Science                   549
Series                    548
Cookbooks                 542
Journals                  535
Math                      517
Name: count, dtype: int64

In [39]:
col_list_obj = df.select_dtypes(include=['object']).columns.to_list()

In [40]:
col_list_obj

['self-learning capability?',
 'Extra-courses did',
 'reading and writing skills',
 'memory capability score',
 'Interested subjects',
 'interested in games',
 'Interested Type of Books',
 'Gentle or Tuff behaviour?',
 'Management or Technical',
 'Salary/work',
 'hard/smart worker',
 'worked in teams ever?',
 'Introvert',
 'Suggested Job Role']

In [41]:
def labelEncoding(df, columns):
    encoders = {}
    for col in columns:
        le = preprocessing.LabelEncoder().fit(df[col])
        df[col] = le.transform(df[col])
        encoders[col] = le
    return df, encoders

In [42]:
def label_encode_columns_w_fit_encoders(df, columns, encoders):
    for col in columns:
        le = encoders.get(col)
        df[col] = le.transform(df[col])
    return df

In [43]:
df, label_encoders = labelEncoding(df, col_list_obj)

In [44]:
df.head()

,Hours working per day,public speaking points,self-learning capability?,Extra-courses did,reading and writing skills,memory capability score,Interested subjects,interested in games,Interested Type of Books,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,9,8,1,1,0,0,4,0,21,1,0,0,0,1,0,7
1,12,3,0,1,2,1,7,1,5,0,1,0,0,0,1,18
2,11,3,0,1,2,0,6,1,29,1,0,1,0,0,1,18
3,7,5,1,0,1,0,7,0,23,0,0,1,1,1,1,28
4,4,3,0,0,2,0,0,1,7,1,0,1,0,1,1,2

In [45]:
df.dtypes

Hours working per day         int64
public speaking points        int64
self-learning capability?     int64
Extra-courses did             int64
reading and writing skills    int64
memory capability score       int64
Interested subjects           int64
interested in games           int64
Interested Type of Books      int64
Gentle or Tuff behaviour?     int64
Management or Technical       int64
Salary/work                   int64
hard/smart worker             int64
worked in teams ever?         int64
Introvert                     int64
Suggested Job Role            int64
dtype: object

In [46]:
df.describe()

,Hours working per day,public speaking points,self-learning capability?,Extra-courses did,reading and writing skills,memory capability score,Interested subjects,interested in games,Interested Type of Books,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
count,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000,19996.00000,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000
mean,7.985397,5.012503,0.505101,0.497550,0.999200,1.000450,4.506301,0.499200,15.213093,0.49845,0.502400,0.496099,0.502250,0.497249,0.504801,16.502701
std,2.593736,2.588942,0.499986,0.500006,0.817904,0.816833,2.873652,0.500012,8.661288,0.50001,0.500007,0.499997,0.500007,0.500005,0.499989,9.639039
min,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.000000,3.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,8.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000
50%,8.000000,5.000000,1.000000,0.000000,1.000000,1.000000,5.000000,0.000000,15.000000,0.00000,1.000000,0.000000,1.000000,0.000000,1.000000,16.000000
75%,10.000000,7.000000,1.000000,1.000000,2.000000,2.000000,7.000000,1.000000,23.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,25.000000
max,12.000000,9.000000,1.000000,1.000000,2.000000,2.000000,9.000000,1.000000,30.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,33.000000

In [47]:
int_columns = list(set(df.columns).difference(set(col_list_obj)))

In [48]:
len(int_columns)

2

In [49]:
data_int = df[int_columns]

In [50]:
df[int_columns] = df[int_columns].fillna(0)

In [51]:
# def normalization(new_data, x):
#     for x in new_data[x]:
#         new_data[x] -= new_data[x].mean()
#         new_data[x] /= new_data[x].std()
#     return new_data

In [52]:
# df = normalization(df, int_columns)
# scaler = MinMaxScaler()
# df[int_columns] = scaler.fit_transform(df[int_columns])

In [53]:
df

,Hours working per day,public speaking points,self-learning capability?,Extra-courses did,reading and writing skills,memory capability score,Interested subjects,interested in games,Interested Type of Books,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,9,8,1,1,0,0,4,0,21,1,0,0,0,1,0,7
1,12,3,0,1,2,1,7,1,5,0,1,0,0,0,1,18
2,11,3,0,1,2,0,6,1,29,1,0,1,0,0,1,18
3,7,5,1,0,1,0,7,0,23,0,0,1,1,1,1,28
4,4,3,0,0,2,0,0,1,7,1,0,1,0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,4,8,0,0,2,0,3,1,17,1,0,0,1,1,0,29
19996,7,8,0,0,1,0,2,1,7,1,0,0,0,0,1,10
19997,7,3,1,1,1,0,7,1,10,0,1,1,0,0,1,1
19998,5,5,0,0,2,2,1,0,29,0,0,1,1,1,0,24
19999,7,6,1,1,0,0,1,0,6,0,0,1,0,1,0,0

In [54]:
df.describe()

,Hours working per day,public speaking points,self-learning capability?,Extra-courses did,reading and writing skills,memory capability score,Interested subjects,interested in games,Interested Type of Books,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
count,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000,19996.00000,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000,19996.000000
mean,7.985397,5.012503,0.505101,0.497550,0.999200,1.000450,4.506301,0.499200,15.213093,0.49845,0.502400,0.496099,0.502250,0.497249,0.504801,16.502701
std,2.593736,2.588942,0.499986,0.500006,0.817904,0.816833,2.873652,0.500012,8.661288,0.50001,0.500007,0.499997,0.500007,0.500005,0.499989,9.639039
min,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.000000,3.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,8.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000
50%,8.000000,5.000000,1.000000,0.000000,1.000000,1.000000,5.000000,0.000000,15.000000,0.00000,1.000000,0.000000,1.000000,0.000000,1.000000,16.000000
75%,10.000000,7.000000,1.000000,1.000000,2.000000,2.000000,7.000000,1.000000,23.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,25.000000
max,12.000000,9.000000,1.000000,1.000000,2.000000,2.000000,9.000000,1.000000,30.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,33.000000

In [55]:
X = df[df.columns.difference(['Suggested Job Role'])]
y = df['Suggested Job Role']

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
def pred_metrics(model, X_train, y_train, X_test, y_test):
    print('Train')
    y_pred_train = model.predict(X_train)
    print('Misclassified samples: {}'.format((y_train != y_pred_train).sum()))
    print('Train Accuracy: {:.2f}'.format(metrics.accuracy_score(y_train, y_pred_train)))
    
    print('Test')
    y_pred_test = model.predict(X_test)
    print('Misclassified samples: {}'.format((y_test != y_pred_test).sum()))
    print('Test Accuracy: {:.2f}'.format(metrics.accuracy_score(y_test, y_pred_test)))
    
    return y_pred_test

In [58]:
dectree = DecisionTreeClassifier(max_depth=5, max_leaf_nodes=17)
dectree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, max_leaf_nodes=17)

In [59]:
y_pred_log_test = pred_metrics(dectree, X_train, y_train, X_test, y_test)

Train
Misclassified samples: 15063
Train Accuracy: 0.06
Test
Misclassified samples: 3767
Test Accuracy: 0.06

In [60]:
y_pred_train = dectree.predict(X_train)
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       443
           1       0.00      0.00      0.00       437
           2       0.08      0.06      0.07       446
           3       0.00      0.00      0.00       474
           4       0.00      0.00      0.00       458
           5       0.00      0.00      0.00       460
           6       0.12      0.01      0.02       473
           7       0.05      0.04      0.04       460
           8       0.30      0.01      0.01       469
           9       0.10      0.04      0.06       460
          10       0.09      0.04      0.05       439
          11       0.08      0.01      0.02       440
          12       0.00      0.00      0.00       429
          13       0.00      0.00      0.00       472
          14       0.11      0.01      0.02       428
          15       0.00      0.00      0.00       514
          16       0.06      0.94      0.11       870
          17       0.00      0.00      0.00       508
          18       0.00      0.00      0.00       469
          19       0.00      0.00      0.00       412
          20       0.00      0.00      0.00       490
          21       0.07      0.02      0.03       448
          22       0.00      0.00      0.00       484
          23       0.00      0.00      0.00       476
          24       0.00      0.00      0.00       456
          25       0.00      0.00      0.00       437
          26       0.00      0.00      0.00       469
          27       0.00      0.00      0.00       443
          28       0.00      0.00      0.00       440
          29       0.00      0.00      0.00       441
          30       0.00      0.00      0.00       455
          31       0.18      0.02      0.04       461
          32       0.00      0.00      0.00       482
          33       0.00      0.00      0.00       453

    accuracy                           0.06     15996
   macro avg       0.04      0.04      0.01     15996
weighted avg       0.04      0.06      0.02     15996

/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [61]:
svm_m = svm.SVC().fit(X_train, y_train)

In [62]:
y_pred = pred_metrics(svm_m, X_train, y_train, X_test, y_test)

Train
Misclassified samples: 15126
Train Accuracy: 0.05
Test
Misclassified samples: 3758
Test Accuracy: 0.06

In [63]:
rfc = RandomForestClassifier(n_estimators=100, max_depth=5, max_leaf_nodes=17, random_state=0)
rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, max_leaf_nodes=17, random_state=0)

In [64]:
y_pred_log_test = pred_metrics(rfc, X_train, y_train, X_test, y_test)

Train
Misclassified samples: 15126
Train Accuracy: 0.05
Test
Misclassified samples: 3758
Test Accuracy: 0.06

In [65]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [66]:
y_pred_log_test = pred_metrics(knn, X_train, y_train, X_test, y_test)

Train
Misclassified samples: 11930
Train Accuracy: 0.25
Test
Misclassified samples: 3869
Test Accuracy: 0.03

In [67]:
gb = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3)
gb.fit(X_train, y_train)

GradientBoostingClassifier()

In [68]:
y_pred_log_test = pred_metrics(gb, X_train, y_train, X_test, y_test)

Train
Misclassified samples: 13667
Train Accuracy: 0.15
Test
Misclassified samples: 3839
Test Accuracy: 0.04

In [69]:
import joblib

In [70]:
joblib.dump(dectree, "best_model.joblib")

['best_model.joblib']

In [71]:
input = df.iloc[4].to_dict()
input

{'Hours working per day': 4,
 'public speaking points': 3,
 'self-learning capability?': 0,
 'Extra-courses did': 0,
 'reading and writing skills': 2,
 'memory capability score': 0,
 'Interested subjects': 0,
 'interested in games': 1,
 'Interested Type of Books': 7,
 'Gentle or Tuff behaviour?': 1,
 'Management or Technical': 0,
 'Salary/work': 1,
 'hard/smart worker': 0,
 'worked in teams ever?': 1,
 'Introvert': 1,
 'Suggested Job Role': 2}

In [72]:
input_data = {'Hours working per day': 4,
 'public speaking points': 3,
 'self-learning capability?': 'no',
 'Extra-courses did': 'yes',
 'reading and writing skills': 'poor',
 'memory capability score': 'excellent',
 'Interested subjects': 'Computer Architecture',
 'interested in games': 'yes',
 'Interested Type of Books': 'Cookbooks',
 'Gentle or Tuff behaviour?': 'stubborn',
 'Management or Technical': 'Management',
 'Salary/work': 'work',
 'hard/smart worker': 'hard worker',
 'worked in teams ever?': 'yes',
 'Introvert': 'yes',
 'Suggested Job Role': 'Business Systems Analyst'}
input_data

{'Hours working per day': 4,
 'public speaking points': 3,
 'self-learning capability?': 'no',
 'Extra-courses did': 'yes',
 'reading and writing skills': 'poor',
 'memory capability score': 'excellent',
 'Interested subjects': 'Computer Architecture',
 'interested in games': 'yes',
 'Interested Type of Books': 'Cookbooks',
 'Gentle or Tuff behaviour?': 'stubborn',
 'Management or Technical': 'Management',
 'Salary/work': 'work',
 'hard/smart worker': 'hard worker',
 'worked in teams ever?': 'yes',
 'Introvert': 'yes',
 'Suggested Job Role': 'Business Systems Analyst'}

In [73]:
input_col_list = col_list_obj[:-1]

In [74]:
input_df = pd.DataFrame([input_data])
input_encoded = label_encode_columns_w_fit_encoders(df=input_df, columns=col_list_obj, encoders=label_encoders)
input_encoded

,Hours working per day,public speaking points,self-learning capability?,Extra-courses did,reading and writing skills,memory capability score,Interested subjects,interested in games,Interested Type of Books,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,4,3,0,1,2,0,0,1,7,1,0,1,0,1,1,2

In [78]:
input = input_encoded[df.columns.difference(['Suggested Job Role'])]
input

,Extra-courses did,Gentle or Tuff behaviour?,Hours working per day,Interested Type of Books,Interested subjects,Introvert,Management or Technical,Salary/work,hard/smart worker,interested in games,memory capability score,public speaking points,reading and writing skills,self-learning capability?,worked in teams ever?
0,1,1,4,7,0,1,0,1,0,1,0,3,2,0,1

In [80]:
model = joblib.load("best_model.joblib")
predicted_label = model.predict(input)
predicted_label

array([16])

In [81]:
def decode_label(column, label, encoders):
    le = encoders.get(column)
    decoded_label = le.inverse_transform([label])

    return decoded_label[0]

In [83]:
decoded_label = decode_label('Suggested Job Role', predicted_label[0], label_encoders)
decoded_label

'Network Security Administrator'